# ═══════════════════════════════════════════════════════════════════════════════
# NixOS Hardware Monitoring & Fan Control Module
# ═══════════════════════════════════════════════════════════════════════════════
# Comprehensive sensor detection, thermal monitoring, and fan validation
# For Colorful X15 XS with Intel i5-12500H + NVIDIA RTX 3050 Ti
# ═══════════════════════════════════════════════════════════════════════════════

{ config, lib, pkgs, ... }:

let
  cfg = config.modules.hardwareMonitor;
  
  # ═══════════════════════════════════════════════════════════════════════════
  # SENSORS CONFIGURATION (lm-sensors)
  # ═══════════════════════════════════════════════════════════════════════════
  
  sensorsConfig = ''
    # Generated by sensors-detect on NixOS
    # This file is loaded by the lm-sensors service
    
    # Intel Core 12th Gen thermal zones
    chip "coretemp-isa-*" {
      label temp1 "Package"
      label temp2 "Core 0"
      label temp3 "Core 1"
      label temp4 "Core 2"
      label temp5 "Core 3"
      
      # Thermal thresholds for alerts
      set temp1_max 85
      set temp1_crit 100
      set temp2_max 85
      set temp2_crit 100
      ignore temp6
      ignore temp7
      ignore temp8
    }
    
    # ACPI thermal zones
    chip "acpitz-acpi-*" {
      label temp1 "ACPI Thermal Zone 0"
    }
    
    # NVMe SSD temperature
    chip "nvme-pci-*" {
      label temp1 "Composite"
      label temp2 "Sensor 1"
      label temp3 "Sensor 2"
      
      set temp1_max 84
      set temp1_crit 88
      ignore temp4
      ignore temp5
      ignore temp6
      ignore temp7
      ignore temp8
    }
    
    # Intel PCH (Platform Controller Hub)
    chip "pch_cannonlake-*" {
      label temp1 "PCH Temperature"
    }
  '';

  # ═══════════════════════════════════════════════════════════════════════════
  # PYTHON MONITORING DAEMON
  # ═══════════════════════════════════════════════════════════════════════════
  
  monitorDaemon = pkgs.writeScriptBin "x15-hwmon-daemon" ''
    #!${pkgs.python3.withPackages (ps: with ps; [
      ps.psutil
      ps.pyserial
    ])}/bin/python3
    
    import os
    import sys
    import json
    import time
    import struct
    import subprocess
    from pathlib import Path
    from datetime import datetime
    
    class HardwareMonitor:
        def __init__(self):
            self.data_dir = Path(os.environ.get('XDG_RUNTIME_DIR', '/tmp')) / 'x15-hwmon'
            self.data_dir.mkdir(parents=True, exist_ok=True)
            self.running = True
            self.sensors_available = self._detect_sensors()
            
        def _detect_sensors(self):
            """Detect available hardware sensors"""
            sensors = {
                'cpu_temp': [],
                'fan_speeds': [],
                'gpu_temp': None,
                'nvme_temp': [],
                'battery': None
            }
            
            # Detect CPU thermal zones
            for zone in Path('/sys/class/thermal').glob('thermal_zone*'):
                try:
                    zone_type = (zone / 'type').read_text().strip()
                    if 'x86_pkg_temp' in zone_type or 'coretemp' in zone_type:
                        sensors['cpu_temp'].append(str(zone))
                except:
                    pass
            
            # Detect hwmon devices (fans, additional temps)
            for hwmon in Path('/sys/class/hwmon').glob('hwmon*'):
                try:
                    name = (hwmon / 'name').read_text().strip()
                    
                    # Fan detection
                    for fan in hwmon.glob('fan*_input'):
                        sensors['fan_speeds'].append({
                            'path': str(fan),
                            'label': f"{name}_{fan.stem}"
                        })
                    
                    # NVMe temperature
                    if 'nvme' in name:
                        for temp in hwmon.glob('temp*_input'):
                            sensors['nvme_temp'].append(str(temp))
                            
                except:
                    pass
            
            # NVIDIA GPU detection
            try:
                result = subprocess.run(['nvidia-smi', '--query-gpu=temperature.gpu', 
                                        '--format=csv,noheader'], 
                                       capture_output=True, text=True, timeout=2)
                if result.returncode == 0:
                    sensors['gpu_temp'] = 'nvidia'
            except:
                pass
            
            # Battery detection
            for bat in Path('/sys/class/power_supply').glob('BAT*'):
                sensors['battery'] = str(bat)
            
            return sensors
        
        def read_cpu_temp(self):
            """Read CPU package temperature"""
            temps = []
            for zone_path in self.sensors_available['cpu_temp']:
                try:
                    temp = int(Path(zone_path) / 'temp') / 1000
                    temps.append(temp)
                except:
                    pass
            return max(temps) if temps else None
        
        def read_fan_speeds(self):
            """Read all fan speeds"""
            speeds = {}
            for fan in self.sensors_available['fan_speeds']:
                try:
                    speed = int(Path(fan['path']).read_text().strip())
                    speeds[fan['label']] = speed
                except:
                    pass
            return speeds
        
        def read_gpu_temp(self):
            """Read NVIDIA GPU temperature"""
            if self.sensors_available['gpu_temp'] == 'nvidia':
                try:
                    result = subprocess.run(['nvidia-smi', '--query-gpu=temperature.gpu',
                                          '--format=csv,noheader'],
                                         capture_output=True, text=True, timeout=2)
                    return int(result.stdout.strip()) if result.returncode == 0 else None
                except:
                    return None
            return None
        
        def read_cpu_freq(self):
            """Read CPU frequency info"""
            freqs = []
            for cpu in Path('/sys/devices/system/cpu').glob('cpu[0-9]*'):
                try:
                    freq = int((cpu / 'cpufreq/scaling_cur_freq').read_text()) / 1000
                    freqs.append(freq)
                except:
                    pass
            
            if freqs:
                return {
                    'min': min(freqs),
                    'max': max(freqs),
                    'avg': sum(freqs) / len(freqs)
                }
            return None
        
        def read_power(self):
            """Read power consumption if available"""
            power = {}
            
            # Battery power
            if self.sensors_available['battery']:
                try:
                    bat_path = Path(self.sensors_available['battery'])
                    power['battery'] = {
                        'capacity': int((bat_path / 'capacity').read_text()),
                        'status': (bat_path / 'status').read_text().strip(),
                        'power_now': int((bat_path / 'power_now').read_text()) / 1000000
                    }
                except:
                    pass
            
            # RAPL power if available
            for rapl in Path('/sys/class/powercap').glob('intel-rapl:*'):
                try:
                    name = (rapl / 'name').read_text().strip()
                    energy = int((rapl / 'energy_uj').read_text())
                    power[name] = energy
                except:
                    pass
            
            return power
        
        def read_memory(self):
            """Read memory statistics"""
            mem = {}
            try:
                with open('/proc/meminfo') as f:
                    for line in f:
                        if 'MemTotal:' in line:
                            mem['total'] = int(line.split()[1]) / 1024
                        elif 'MemAvailable:' in line:
                            mem['available'] = int(line.split()[1]) / 1024
                        elif 'Buffers:' in line:
                            mem['buffers'] = int(line.split()[1]) / 1024
                        elif 'Cached:' in line:
                            mem['cached'] = int(line.split()[1]) / 1024
                        elif 'SwapTotal:' in line:
                            mem['swap_total'] = int(line.split()[1]) / 1024
                        elif 'SwapFree:' in line:
                            mem['swap_free'] = int(line.split()[1]) / 1024
                
                if 'total' in mem and 'available' in mem:
                    mem['used'] = mem['total'] - mem['available']
                    mem['percent'] = (mem['used'] / mem['total']) * 100
            except:
                pass
            return mem
        
        def read_load(self):
            """Read system load"""
            try:
                with open('/proc/loadavg') as f:
                    load = f.read().split()
                    return {
                        '1min': float(load[0]),
                        '5min': float(load[1]),
                        '15min': float(load[2])
                    }
            except:
                return None
        
        def read_net_io(self):
            """Read network I/O statistics"""
            net = {'rx_bytes': 0, 'tx_bytes': 0}
            try:
                for iface in Path('/sys/class/net').iterdir():
                    if iface.name == 'lo':
                        continue
                    try:
                        rx = int((iface / 'statistics/rx_bytes').read_text())
                        tx = int((iface / 'statistics/tx_bytes').read_text())
                        net['rx_bytes'] += rx
                        net['tx_bytes'] += tx
                    except:
                        pass
            except:
                pass
            return net
        
        def collect(self):
            """Collect all metrics"""
            return {
                'timestamp': datetime.now().isoformat(),
                'cpu': {
                    'temperature': self.read_cpu_temp(),
                    'frequency': self.read_cpu_freq(),
                    'load': self.read_load()
                },
                'fans': self.read_fan_speeds(),
                'gpu': {
                    'temperature': self.read_gpu_temp()
                },
                'memory': self.read_memory(),
                'power': self.read_power(),
                'network': self.read_net_io()
            }
        
        def write_data(self, data):
            """Write data to shared files for other processes"""
            # JSON format for Quickshell
            json_file = self.data_dir / 'hwmon.json'
            json_file.write_text(json.dumps(data, indent=2))
            
            # Simple format for shell scripts
            simple_file = self.data_dir / 'hwmon.txt'
            lines = [
                f"CPU_TEMP={data['cpu']['temperature'] or 'N/A'}",
                f"CPU_FREQ={data['cpu']['frequency']['avg'] if data['cpu']['frequency'] else 'N/A'}",
                f"LOAD_1MIN={data['cpu']['load']['1min'] if data['cpu']['load'] else 'N/A'}",
                f"GPU_TEMP={data['gpu']['temperature'] or 'N/A'}",
                f"MEM_PERCENT={data['memory'].get('percent', 'N/A')}",
            ]
            
            # Add fan speeds
            for fan, speed in data['fans'].items():
                lines.append(f"FAN_{fan.upper()}={speed}")
            
            simple_file.write_text('\n'.join(lines))
        
        def run(self):
            """Main monitoring loop"""
            print(f"Hardware Monitor started. Data directory: {self.data_dir}")
            
            while self.running:
                try:
                    data = self.collect()
                    self.write_data(data)
                    time.sleep(cfg.pollInterval)
                except Exception as e:
                    print(f"Error: {e}", file=sys.stderr)
                    time.sleep(1)
    
    if __name__ == '__main__':
        monitor = HardwareMonitor()
        
        # Handle signals gracefully
        import signal
        signal.signal(signal.SIGTERM, lambda s, f: setattr(monitor, 'running', False))
        signal.signal(signal.SIGINT, lambda s, f: setattr(monitor, 'running', False))
        
        monitor.run()
  '';

  # ═══════════════════════════════════════════════════════════════════════════
  # FAN CONTROL VALIDATION SCRIPT
  # ═══════════════════════════════════════════════════════════════════════════
  
  fanValidator = pkgs.writeShellScriptBin "x15-fan-validate" ''
    #!${pkgs.bash}/bin/bash
    set -euo pipefail
    
    LOG_FILE="/tmp/fan_validation_$(date +%Y%m%d_%H%M%S).log"
    VERBOSE="''${VERBOSE:-0}"
    
    log() {
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
    }
    
    error() {
      echo "[ERROR] $*" | tee -a "$LOG_FILE" >&2
    }
    
    # ═════════════════════════════════════════════════════════════════════════
    # SENSOR DETECTION
    # ═════════════════════════════════════════════════════════════════════════
    
    detect_sensors() {
      log "═══════════════════════════════════════════════════════════"
      log "  Hardware Sensor Detection"
      log "═══════════════════════════════════════════════════════════"
      
      # Check lm-sensors
      if command -v sensors &> /dev/null; then
        log ">>> lm-sensors installed"
        sensors 2>/dev/null | head -20 | while read line; do
          log "    $line"
        done
      else
        error "lm-sensors not installed"
      fi
      
      # Detect thermal zones
      log ">>> Thermal Zones:"
      for zone in /sys/class/thermal/thermal_zone*; do
        if [ -d "$zone" ]; then
          name=$(cat "$zone/type" 2>/dev/null || echo "unknown")
          temp=$(cat "$zone/temp" 2>/dev/null || echo 0)
          temp_c=$(echo "scale=1; $temp/1000" | bc 2>/dev/null || echo "N/A")
          log "    $(basename $zone): $name = ''${temp_c}°C"
        fi
      done
      
      # Detect hwmon devices
      log ">>> Hardware Monitors (hwmon):"
      for hwmon in /sys/class/hwmon/hwmon*; do
        if [ -d "$hwmon" ]; then
          name=$(cat "$hwmon/name" 2>/dev/null || echo "unknown")
          log "    $(basename $hwmon): $name"
          
          # List sensors
          for sensor in "$hwmon"/*_input; do
            if [ -f "$sensor" ]; then
              label=$(cat "''${sensor%_input}_label" 2>/dev/null || basename "$sensor")
              val=$(cat "$sensor" 2>/dev/null || echo 0)
              log "      $label: $val"
            fi
          done
        fi
      done
    }
    
    # ═════════════════════════════════════════════════════════════════════════
    # FAN SPEED VALIDATION
    # ═════════════════════════════════════════════════════════════════════════
    
    validate_fan_response() {
      log ""
      log "═══════════════════════════════════════════════════════════"
      log "  Fan Response Validation"
      log "═══════════════════════════════════════════════════════════"
      
      # Read initial fan speed
      FAN_BEFORE=$(cat /sys/class/hwmon/hwmon*/fan1_input 2>/dev/null | head -1 || echo 0)
      TEMP_BEFORE=$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | head -1 || echo 0)
      TEMP_BEFORE_C=$(echo "scale=1; $TEMP_BEFORE/1000" | bc 2>/dev/null || echo "N/A")
      
      log ">>> Initial State:"
      log "    Fan Speed: ''${FAN_BEFORE} RPM"
      log "    CPU Temp: ''${TEMP_BEFORE_C}°C"
      
      # Check NBFC status
      if systemctl is-active --quiet nbfc_service 2>/dev/null; then
        log ">>> NBFC Service: ACTIVE"
      else
        error "NBFC Service: NOT RUNNING"
        systemctl status nbfc_service 2>&1 | head -5 | while read line; do
          log "    $line"
        done
        return 1
      fi
      
      # Verify fan curve progression
      log ""
      log ">>> Testing Fan Curve Progression..."
      
      # Create temporary load (if stress-ng available)
      if command -v stress-ng &> /dev/null; then
        log "    Starting 10s thermal load test..."
        
        stress-ng --cpu $(nproc) --timeout 10 --quiet &
        STRESS_PID=$!
        
        # Monitor during stress
        for i in {1..5}; do
          sleep 2
          FAN=$(cat /sys/class/hwmon/hwmon*/fan1_input 2>/dev/null | head -1 || echo 0)
          TEMP=$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | head -1 || echo 0)
          TEMP_C=$(echo "scale=1; $TEMP/1000" | bc 2>/dev/null || echo "N/A")
          log "    T+''${i}s: Fan=''${FAN} RPM, Temp=''${TEMP_C}°C"
        done
        
        wait $STRESS_PID 2>/dev/null || true
        
        # Wait for cooldown
        log "    Waiting 15s for cooldown..."
        sleep 15
        
        FAN_AFTER=$(cat /sys/class/hwmon/hwmon*/fan1_input 2>/dev/null | head -1 || echo 0)
        TEMP_AFTER=$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | head -1 || echo 0)
        TEMP_AFTER_C=$(echo "scale=1; $TEMP_AFTER/1000" | bc 2>/dev/null || echo "N/A")
        
        log ""
        log ">>> Post-Test State:"
        log "    Fan Speed: ''${FAN_AFTER} RPM"
        log "    CPU Temp: ''${TEMP_AFTER_C}°C"
        
        # Validate response
        if [ "$FAN_AFTER" -lt "$FAN_BEFORE" ] || [ "$FAN_AFTER" -eq 0 ]; then
          if [ "$TEMP_AFTER_C" != "N/A" ] && [ "$(echo "$TEMP_AFTER_C < 50" | bc 2>/dev/null || echo 0)" -eq 1 ]; then
            log "    [✓] Fan response valid (temp normalized)"
          else
            error "Fan response may be abnormal (speed did not reduce with temp)"
          fi
        else
          log "    [!] Fan still elevated (may be normal if temp is high)"
        fi
      else
        log "    stress-ng not available - skipping active test"
        log "    Install with: nix-shell -p stress-ng"
      fi
      
      return 0
    }
    
    # ═════════════════════════════════════════════════════════════════════════
    # PWM CURVE VERIFICATION
    # ═════════════════════════════════════════════════════════════════════════
    
    verify_pwm_curve() {
      log ""
      log "═══════════════════════════════════════════════════════════"
      log "  PWM Curve Verification"
      log "═══════════════════════════════════════════════════════════"
      
      # Check NBFC configuration
      if [ -f /etc/nbfc/nbfc.json ]; then
        log ">>> NBFC Configuration:"
        ${pkgs.jq}/bin/jq '.FanConfigurations[0].TemperatureThresholds' /etc/nbfc/nbfc.json 2>/dev/null |
          while read line; do
            log "    $line"
          done
        
        log ""
        log ">>> Critical Temperature: $(cat /etc/nbfc/nbfc.json | ${pkgs.jq}/bin/jq -r '.CriticalTemperature')°C"
        log ">>> Poll Interval: $(cat /etc/nbfc/nbfc.json | ${pkgs.jq}/bin/jq -r '.EcPollInterval')ms"
      else
        error "NBFC config not found at /etc/nbfc/nbfc.json"
      fi
      
      # Display current thermal thresholds
      log ""
      log ">>> Expected Behavior (from config):"
      log "    < 42°C: Fan OFF (0%)"
      log "    42-55°C: Low speed (20%)"
      log "    55-65°C: Moderate (40%)"
      log "    65-72°C: Active (65%)"
      log "    72-80°C: Aggressive (85%)"
      log "    > 80°C: Full blast (100%)"
      log "    > 90°C: Critical emergency"
    }
    
    # ═════════════════════════════════════════════════════════════════════════
    # MAIN EXECUTION
    # ═════════════════════════════════════════════════════════════════════════
    
    main() {
      echo "X15 Hardware Monitor - Fan Validation"
      echo "Log file: $LOG_FILE"
      echo ""
      
      detect_sensors
      validate_fan_response
      verify_pwm_curve
      
      log ""
      log "═══════════════════════════════════════════════════════════"
      log "  Validation Complete"
      log "  Log saved to: $LOG_FILE"
      log "═══════════════════════════════════════════════════════════"
    }
    
    main "$@"
  '';

  # ═══════════════════════════════════════════════════════════════════════════
  # THERMAL STRESS TEST SCRIPT
  # ═══════════════════════════════════════════════════════════════════════════
  
  thermalStressTest = pkgs.writeShellScriptBin "x15-thermal-validation" ''
    #!${pkgs.bash}/bin/bash
    set -euo pipefail
    
    DURATION="''${1:-300}"
    OUTPUT_FILE="/tmp/thermal_validation_$(date +%Y%m%d_%H%M%S).csv"
    CORES=$(nproc)
    
    echo "═══════════════════════════════════════════════════════════"
    echo "  Thermal Validation Suite"
    echo "  Duration: ''${DURATION}s | Cores: $CORES"
    echo "═══════════════════════════════════════════════════════════"
    
    # Setup CSV header
    echo "time,cpu_temp,cpu_freq,fan_rpm,gpu_temp,load_1min,throttle_count" > "$OUTPUT_FILE"
    
    cleanup() {
      echo -e "\n>>> Stopping validation..."
      pkill -f stress-ng 2>/dev/null || true
      pkill -f "thermal monitor" 2>/dev/null || true
      
      # Generate report
      echo ""
      echo ">>> Generating Thermal Report..."
      echo "    Data: $OUTPUT_FILE"
      
      if [ -s "$OUTPUT_FILE" ] && [ $(wc -l < "$OUTPUT_FILE") -gt 1 ]; then
        echo ""
        echo "═══════════════════════════════════════════════════════════"
        echo "  Thermal Statistics"
        echo "═══════════════════════════════════════════════════════════"
        
        # Calculate statistics using awk
        tail -n +2 "$OUTPUT_FILE" | awk -F',' '
          NR==1 {min_temp=max_temp=avg_temp=$2; min_freq=max_freq=avg_freq=$3; min_fan=max_fan=avg_fan=$4}
          {
            temps[NR]=$2; freqs[NR]=$3; fans[NR]=$4
            if ($2 < min_temp) min_temp=$2; if ($2 > max_temp) max_temp=$2
            if ($3 < min_freq) min_freq=$3; if ($3 > max_freq) max_freq=$3
            if ($4 < min_fan) min_fan=$4; if ($4 > max_fan) max_fan=$4
            sum_temp+=$2; sum_freq+=$3; sum_fan+=$4; count++
          }
          END {
            print "Temperature (°C):"
            print "  Min: " min_temp " | Max: " max_temp " | Avg: " sum_temp/count
            print ""
            print "CPU Frequency (MHz):"
            print "  Min: " min_freq " | Max: " max_freq " | Avg: " sum_freq/count
            print ""
            print "Fan Speed (RPM):"
            print "  Min: " min_fan " | Max: " max_fan " | Avg: " sum_fan/count
          }'
        
        echo ""
        echo ">>> Fan Response Check:"
        # Check if fan increased with temperature
        START_FAN=$(tail -n +2 "$OUTPUT_FILE" | head -1 | cut -d',' -f4)
        MAX_FAN=$(tail -n +2 "$OUTPUT_FILE" | awk -F',' 'BEGIN{max=0} {if($4>max) max=$4} END{print max}')
        
        if [ "$MAX_FAN" -gt "$START_FAN" ]; then
          echo "    [✓] Fan response detected ($START_FAN -> $MAX_FAN RPM)"
        else
          echo "    [!] Fan did not increase significantly"
        fi
        
        # Check thermal throttling
        THROTTLE_COUNT=$(tail -1 "$OUTPUT_FILE" | cut -d',' -f7)
        if [ "$THROTTLE_COUNT" -gt 1 ]; then
          echo "    [!] Thermal throttling detected ($THROTTLE_COUNT events)"
        else
          echo "    [✓] No thermal throttling detected"
        fi
      fi
      
      exit 0
    }
    trap cleanup SIGINT SIGTERM EXIT
    
    # Background monitoring
    monitor() {
      local start_time=$(date +%s)
      
      while true; do
        local elapsed=$(( $(date +%s) - start_time ))
        
        # Read sensors
        local cpu_temp=$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | head -1 || echo 0)
        local cpu_freq=$(cat /proc/cpuinfo | grep "cpu MHz" | head -1 | awk '{print $4}' || echo 0)
        local fan_rpm=$(cat /sys/class/hwmon/hwmon*/fan1_input 2>/dev/null | head -1 || echo 0)
        local load=$(cat /proc/loadavg | cut -d' ' -f1)
        local throttle=$(cat /sys/devices/system/cpu/cpu0/thermal_throttle/throttle_count 2>/dev/null || echo 0)
        
        # GPU temperature if available
        local gpu_temp=0
        if command -v nvidia-smi &> /dev/null; then
          gpu_temp=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader 2>/dev/null | head -1 || echo 0)
        fi
        
        echo "$elapsed,$cpu_temp,$cpu_freq,$fan_rpm,$gpu_temp,$load,$throttle" >> "$OUTPUT_FILE"
        
        # Progress display
        printf "\r  Progress: ''${elapsed}s / ''${DURATION}s (Temp: ''${cpu_temp%??}°C, Fan: ''${fan_rpm} RPM)"
        
        sleep 1
      done
    }
    
    # Start monitoring
    echo ">>> Starting thermal monitor..."
    monitor &
    MONITOR_PID=$!
    
    # Start stress test
    sleep 2
    echo ""
    echo ">>> Starting CPU stress test..."
    stress-ng --cpu $CORES --cpu-method all --timeout ''${DURATION}s --quiet 2>&1 &
    STRESS_PID=$!
    
    # Wait for completion
    wait $STRESS_PID 2>/dev/null || true
    
    # Allow cooldown period
    echo ""
    echo ">>> Stress complete. Monitoring cooldown..."
    sleep 30
    
    # Cleanup will run via trap
  '';

in
{
  # ═══════════════════════════════════════════════════════════════════════════
  # OPTIONS
  # ═══════════════════════════════════════════════════════════════════════════
  
  options.modules.hardwareMonitor = {
    enable = lib.mkEnableOption "comprehensive hardware monitoring and fan control";
    
    pollInterval = lib.mkOption {
      type = lib.types.int;
      default = 2;
      description = "Sensor polling interval in seconds";
    };
    
    enableAlerts = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable thermal alert notifications";
    };
    
    alertThresholds = lib.mkOption {
      type = lib.types.submodule {
        options = {
          cpuTemp = lib.mkOption { type = lib.types.int; default = 85; };
          gpuTemp = lib.mkOption { type = lib.types.int; default = 83; };
          fanStop = lib.mkOption { type = lib.types.bool; default = true; };
        };
      };
      default = {};
      description = "Thermal alert thresholds";
    };
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # CONFIGURATION
  # ═══════════════════════════════════════════════════════════════════════════
  
  config = lib.mkIf cfg.enable {
    
    # ── lm-sensors ───────────────────────────────────────────────────────────
    hardware.sensor.iio.enable = true;
    
    environment.etc."sensors.d/x15.conf".text = sensorsConfig;
    
    # ── Monitoring Packages ──────────────────────────────────────────────────
    environment.systemPackages = [
      pkgs.lm_sensors
      pkgs.sensors
      pkgs.stress-ng
      pkgs.sysbench
      monitorDaemon
      fanValidator
      thermalStressTest
      
      (pkgs.writeShellScriptBin "x15-sensors" ''
        #!${pkgs.bash}/bin/bash
        
        show_help() {
          echo "X15 Hardware Monitor - Sensor Interface"
          echo ""
          echo "Usage: x15-sensors [COMMAND]"
          echo ""
          echo "Commands:"
          echo "  status     Show current sensor readings"
          echo "  watch      Continuous monitoring (2s interval)"
          echo "  validate   Run fan control validation"
          echo "  stress     Run thermal stress test"
          echo "  daemon     Start hardware monitoring daemon"
          echo "  json       Output JSON format for Quickshell"
          echo "  help       Show this help message"
        }
        
        show_status() {
          echo "═══════════════════════════════════════════════════════════"
          echo "  X15 Hardware Status - $(date)"
          echo "═══════════════════════════════════════════════════════════"
          
          # Read from daemon if available
          if [ -r "''${XDG_RUNTIME_DIR:-/tmp}/x15-hwmon/hwmon.json" ]; then
            ${pkgs.jq}/bin/jq -r '
              "CPU: \(.cpu.temperature)°C @ \(.cpu.frequency.avg // 0 | floor) MHz",
              "Load: \(.cpu.load."1min")",
              "Memory: \(.memory.percent // 0 | floor)% used",
              "GPU: \(.gpu.temperature // "N/A")°C"
            ' "''${XDG_RUNTIME_DIR:-/tmp}/x15-hwmon/hwmon.json" 2>/dev/null || echo "Daemon data unavailable"
          else
            # Fallback to direct reading
            echo ">>> CPU Temperature:"
            for zone in /sys/class/thermal/thermal_zone*; do
              [ -r "$zone/temp" ] && echo "  $(basename $zone): $(cat $zone/temp | awk '{print $1/1000}')°C"
            done
            
            echo ""
            echo ">>> Fan Speeds:"
            for fan in /sys/class/hwmon/hwmon*/fan*_input; do
              [ -r "$fan" ] && echo "  $fan: $(cat $fan) RPM"
            done
          fi
        }
        
        watch_sensors() {
          while true; do
            clear
            show_status
            sleep 2
          done
        }
        
        output_json() {
          if [ -r "''${XDG_RUNTIME_DIR:-/tmp}/x15-hwmon/hwmon.json" ]; then
            cat "''${XDG_RUNTIME_DIR:-/tmp}/x15-hwmon/hwmon.json"
          else
            echo '{"error": "Daemon not running"}'
          fi
        }
        
        case "''${1:-status}" in
          status)   show_status ;;
          watch)    watch_sensors ;;
          validate) x15-fan-validate ;;
          stress)   x15-thermal-validation ;;
          daemon)   x15-hwmon-daemon ;;
          json)     output_json ;;
          help|*)   show_help ;;
        esac
      '')
    ];
    
    # ── Hardware Monitor Daemon Service ──────────────────────────────────────
    systemd.services.x15-hwmon = {
      description = "X15 Hardware Monitor Daemon";
      wantedBy = [ "multi-user.target" ];
      after = [ "systemd-udev-settle.service" ];
      
      serviceConfig = {
        Type = "simple";
        ExecStart = "${monitorDaemon}/bin/x15-hwmon-daemon";
        Restart = "on-failure";
        RestartSec = 5;
        
        # Security hardening (read-only sensor access)
        PrivateTmp = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        ReadWritePaths = [ "/tmp" "/run/user" ];
        
        # Device access for sensors
        DeviceAllow = [ "/dev/nvidiactl" "/dev/nvidia*" ];
        SupplementaryGroups = [ "video" ];
      };
      
      environment = {
        XDG_RUNTIME_DIR = "/run/user/0";
      };
    };
    
    # User service for the daemon
    systemd.user.services.x15-hwmon = {
      description = "X15 Hardware Monitor Daemon (User)";
      wantedBy = [ "default.target" ];
      
      serviceConfig = {
        Type = "simple";
        ExecStart = "${monitorDaemon}/bin/x15-hwmon-daemon";
        Restart = "on-failure";
        RestartSec = 5;
      };
    };
    
    # ── Thermal Alert Notifications ──────────────────────────────────────────
    systemd.services.x15-thermal-alert = lib.mkIf cfg.enableAlerts {
      description = "X15 Thermal Alert Monitor";
      wantedBy = [ "multi-user.target" ];
      
      serviceConfig = {
        Type = "simple";
        ExecStart = pkgs.writeShellScript "thermal-alert" ''
          THRESHOLD_CPU="${toString cfg.alertThresholds.cpuTemp}"
          THRESHOLD_GPU="${toString cfg.alertThresholds.gpuTemp}"
          
          while true; do
            # Check CPU temperature
            CPU_TEMP=$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | 
                      awk '{print $1/1000}' | sort -n | tail -1)
            
            if [ "''${CPU_TEMP%.*}" -ge "$THRESHOLD_CPU" ]; then
              ${pkgs.libnotify}/bin/notify-send \
                --urgency=critical \
                "Thermal Alert" \
                "CPU temperature critical: ''${CPU_TEMP}°C" \
                --icon=dialog-warning 2>/dev/null || true
            fi
            
            # Check GPU temperature if nvidia-smi available
            if command -v nvidia-smi &> /dev/null; then
              GPU_TEMP=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader 2>/dev/null | head -1)
              if [ "''${GPU_TEMP%.*}" -ge "$THRESHOLD_GPU" ]; then
                ${pkgs.libnotify}/bin/notify-send \
                  --urgency=critical \
                  "GPU Thermal Alert" \
                  "GPU temperature critical: ''${GPU_TEMP}°C" \
                  --icon=dialog-warning 2>/dev/null || true
              fi
            fi
            
            sleep 10
          done
        '';
        Restart = "on-failure";
      };
    };
  };
}
